{"kind":"symbol","variants":[{"paths":["\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"The location where the error was thrown."}],"metadata":{"modules":[{"name":"NIOHTTP2"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"location","symbolKind":"property","externalID":"s:8NIOHTTP20A6ErrorsO24PushInViolationOfSettingV8locationSSvp","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Linux"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"title":"NIOHTTP2","type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/niohttp2"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors":{"abstract":[{"type":"text","text":"Errors that "},{"type":"reference","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","isActive":true},{"type":"text","text":" raises when handling HTTP\/2 connections."}],"title":"NIOHTTP2Errors","kind":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOHTTP2Errors"}],"type":"topic","url":"\/documentation\/niohttp2\/niohttp2errors","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NIOHTTP2Errors"}]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting/location":{"url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location","abstract":[{"text":"The location where the error was thrown.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"location","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting","abstract":[{"type":"text","text":"An attempt was made to push a stream, even though the settings forbid it."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushInViolationOfSetting"}],"url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting","kind":"symbol","title":"NIOHTTP2Errors.PushInViolationOfSetting","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushInViolationOfSetting"}]}}}