{"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ChannelInboundInvoker"]]},"abstract":[{"type":"text","text":"Called when an inbound operation "},{"code":"Error","type":"codeVoice"},{"type":"text","text":" was caught."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ChannelInboundInvoker\/fireErrorCaught(_:)"},"sections":[],"variants":[{"paths":["\/documentation\/niocore\/channelinboundinvoker\/fireerrorcaught(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fireErrorCaught","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["Linux"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"the error we encountered.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Be aware that for inbound operations this method is called while for outbound operations defined in "},{"code":"ChannelOutboundInvoker","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"the "},{"code":"EventLoopFuture","type":"codeVoice"},{"type":"text","text":" or "},{"code":"EventLoopPromise","type":"codeVoice"},{"type":"text","text":" will be notified."}]}]}],"metadata":{"modules":[{"name":"NIOCore"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fireErrorCaught","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"externalID":"s:7NIOCore21ChannelInboundInvokerP15fireErrorCaughtyys0F0_pF","title":"fireErrorCaught(_:)","roleHeading":"Instance Method","symbolKind":"method","required":true},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOCore":{"url":"\/documentation\/niocore","title":"NIOCore","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","kind":"symbol","type":"topic","abstract":[],"role":"collection"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ChannelInboundInvoker":{"url":"\/documentation\/niocore\/channelinboundinvoker","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChannelInboundInvoker","kind":"identifier"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ChannelInboundInvoker","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Fire inbound events related to a "},{"type":"codeVoice","code":"Channel"},{"text":" through the ","type":"text"},{"code":"ChannelPipeline","type":"codeVoice"},{"text":" until its end is reached or itâ€™s consumed by a ","type":"text"},{"code":"ChannelHandler","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ChannelInboundInvoker","kind":"identifier"}],"title":"ChannelInboundInvoker"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ChannelInboundInvoker/fireErrorCaught(_:)":{"abstract":[{"type":"text","text":"Called when an inbound operation "},{"type":"codeVoice","code":"Error"},{"text":" was caught.","type":"text"}],"kind":"symbol","required":true,"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ChannelInboundInvoker\/fireErrorCaught(_:)","title":"fireErrorCaught(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fireErrorCaught","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/niocore\/channelinboundinvoker\/fireerrorcaught(_:)"}}}