{"kind":"symbol","abstract":[{"text":"More data has been received by a ","type":"text"},{"code":"ByteToMessageHandler","type":"codeVoice"},{"text":" despite the fact that an error has previously been","type":"text"},{"text":" ","type":"text"},{"text":"emitted. The associated ","type":"text"},{"code":"Error","type":"codeVoice"},{"text":" is the error previously emitted and the ","type":"text"},{"code":"ByteBuffer","type":"codeVoice"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" "},{"type":"text","text":"after previously an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" has been sent through the pipeline using "},{"type":"codeVoice","code":"fireErrorCaught"},{"type":"text","text":"."}],"metadata":{"externalID":"s:7NIOCore25ByteToMessageDecoderErrorO014dataReceivedInF5StateyACs0F0_p_AA0B6BufferVtcACmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"NIOCore"}],"title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","symbolKind":"case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError"]]},"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataReceivedInErrorState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ByteBuffer","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["Linux"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteBuffer":{"kind":"symbol","title":"ByteBuffer","abstract":[{"code":"ByteBuffer","type":"codeVoice"},{"type":"text","text":" stores contiguously allocated raw bytes. It is a random and sequential accessible sequence of zero or"},{"type":"text","text":" "},{"type":"text","text":"more bytes (octets)."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteBuffer"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","url":"\/documentation\/niocore\/bytebuffer","navigatorTitle":[{"kind":"identifier","text":"ByteBuffer"}]},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/dataReceivedInErrorState(_:_:)":{"title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":", "},{"preciseIdentifier":"s:7NIOCore10ByteBufferV","kind":"typeIdentifier","text":"ByteBuffer"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"More data has been received by a ","type":"text"},{"code":"ByteToMessageHandler","type":"codeVoice"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"type":"text","text":"emitted. The associated "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" is the error previously emitted and the "},{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" "},{"type":"text","text":"after previously an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" has been sent through the pipeline using "},{"type":"codeVoice","code":"fireErrorCaught"},{"type":"text","text":"."}],"url":"\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","kind":"symbol"},"doc://co.pointfree.VaporRouting/documentation/NIOCore":{"url":"\/documentation\/niocore","title":"NIOCore","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","kind":"symbol","type":"topic","abstract":[],"role":"collection"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteToMessageDecoderError"}],"navigatorTitle":[{"kind":"identifier","text":"ByteToMessageDecoderError"}],"role":"symbol","url":"\/documentation\/niocore\/bytetomessagedecodererror","title":"ByteToMessageDecoderError","abstract":[{"type":"text","text":"Common errors thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s."}],"type":"topic","kind":"symbol"}}}